try:
    result=45/0
#result error
except:
    print('error hapend')
finally:
    print('finally here')    
print('Done')
